name: PageSpeed
run-name: ${{ github.actor }} is running a PageSpeed test 🚀
on: [push]
jobs:
  Run-Page-Speed:
    runs-on: ubuntu-latest
    steps:
      - name: Running Page Speed Insights
        uses: jakepartusch/psi-action@v1.3
        id: psi
        with:
          url: "https://main--adobe-helix-tutorial--nwoodard-cs.hlx.page/"
          threshold: 70
          strategy: mobile
